---
title: "korea Analysis"
author: "nn"
date: '2020 7 17 '
output: html_document
---

# 한국 복지 패널 데이터 분석
---
# 데이터 수집 및 준비
https://www.koweps.re.kr:442

# 데이터 준비
### 1-1 라이브러리 준비
```{r}
# install.packages('foreign')
# install.packages('dplyr')
# install.pakages('ggplot2')
# install.packages('readxl')

library(foreign)
library(dplyr)
library(ggplot2)
library(readxl)
```

### 1-2 데이터 불러오기
```{r}
raw_welfare = read.spss(file='../data/Koweps_hpc10_2015_beta1.sav', to.data.frame = T)
head(raw_welfare)

# 복사본
welfare <- raw_welfare
```
### 1-3 데이터 검토
```{r}
head(welfare)
tail(welfare)
dim(welfare)
str(welfare)
summary(welfare)
View(welfare)
```

### 1-4 특성 선택
```{r}
welfare <- rename(welfare, sex=h10_g3, birth=h10_g4, marriage=h10_g10, religion=h10_g11, income=p1002_8aq1, code_job=h10_eco9, code_region=h10_reg7)
welfare <- welfare[, c('sex','birth','marriage','religion','income','code_job','code_region')]
head(welfare)

```

# 2. 탐색적 데이터 분석

### 2-1 성별에 따른 월급의 차이
```{r}
# 변수 검토
class(welfare$sex)
table(welfare$sex)

# 성별 항목 이름 변경(1:male, 2:female)
welfare$sex <- ifelse(welfare$sex == 1, 'male', 'female')
table(welfare$sex)
qplot(welfare$sex)
```
```{r}
# 월급변수 검토
class(welfare$income)
summary(welfare$income)

qplot(welfare$income) + xlim(0,1000)
```
```{r}
# 월급변수에 대한 전처리 ; 이상치, 결측치
welfare$income <- ifelse(welfare$income %in% c(0,9999), NA, welfare$income)
# 몇개가 결측치인지 확인해보기
table(is.na(welfare$income))
```
```{r}
# 성별에 따른 평균 급여
sex_income <- welfare  %>% group_by(sex) %>% summarise(mean_income = mean(income,na.rm=T))
sex_income
```
```{r}
# 최종 시각화
ggplot(data = sex_income, aes(x = sex, y = mean_income)) + geom_col()
```

### 2-2 나이와 월급의 관계
```{r}
# 나이 변수 검토
class(welfare$birth)
summary(welfare$birth)

qplot(welfare$birth)
```


```{r}
welfare <- welfare %>% mutate(age = (2015-birth+1))
age_income <- welfare %>% filter(!is.na(income)) %>%group_by(age) %>% summarise(mean_income = mean(income))
table(is.na(age_income$mean_income))
age_income %>% arrange(desc(mean_income)) %>% head(5)
```


```{r}
# 최종 시각화
ggplot(data = age_income, aes(x=age_income$age, y = age_income$mean_income)) + geom_line()
```
```{r}
# 연령대로 범주화
# 초년(~30세), 중년(30~59세), 장년(60세 이상)
welfare <- welfare %>% mutate(ageg=ifelse(age<30, 'young', ifelse(age<60, 'middle', 'old')))

table(welfare$ageg)

```
```{r}
# 연령대 별로 월급여 평균
ageg_income <- welfare %>% filter(!is.na(income)) %>%group_by(ageg) %>% summarise(mean_income = mean(income))
ageg_income
ggplot(data=ageg_income, aes(x = ageg, y = mean_income))+geom_col() + scale_x_discrete(limits=c('young','middle', 'old'))

```
```{r}
# 연령대  및 성별에 따른 월급차이
ageg_sex_income <- welfare %>% filter(!is.na(income)) %>%group_by(ageg, sex) %>% summarise(mean_income = mean(income))

ageg_sex_income
```
```{r}
ggplot(ageg_sex_income, aes(ageg, mean_income, fill=sex))+geom_col(position="dodge") + scale_x_discrete(limits=c('young','middle', 'old'))

```
```{r}
age_sex_income <- welfare %>% filter(!is.na(income)) %>% group_by(age, sex) %>% summarise(mean_income = mean(income))

head(age_sex_income)

ggplot(age_sex_income, aes(age, mean_income, col=sex)) + geom_line()

```
### 2-3 직업과 월급의 관계
```{r}
# 직업 변수 검토
class(welfare$code_job)
summary(welfare$code_job)
```
#### 전처리
```{r}
list_job <- read_excel('../data/Koweps_Codebook.xlsx', col_names =T, sheet=2)

head(list_job)
dim(list_job)
```
```{r}
welfare <- left_join(welfare, list_job, by = 'code_job')
head(welfare)
welfare %>% filter(!is.na(code_job)) %>% select(code_job, job) %>% head(10)
```

```{r}
# 직업별 평균급여
job_income <- welfare %>% filter(!is.na(code_job))%>% group_by(job) %>% summarise(mean_income = mean(income, na.rm = T)) %>% arrange(desc(mean_income))

top10 <- head(job_income,10)
low10 <-tail(job_income, 10)

top10
low10
```

```{r}
# 그래프 옆으로 돌리고 눈금 조정하기
ggplot(top10, aes(reorder(job, mean_income), mean_income)) + geom_col() + coord_flip() + ylim(0,850)
```

### 2-4. 성별 직업 빈도
```{r}
# 남성 직업 빈도 상위 10개
male_job <- welfare %>% filter(!is.na(job)) %>% filter(sex == 'male') %>% select(sex, job) %>% group_by(job) %>% summarise(num = n()) %>% arrange(desc(num)) %>% head(10)
male_job
```

```{r}
# 여성 직업 빈도 상위 10개
female_job <- welfare %>% filter(!is.na(job)) %>% filter(sex == 'female') %>% select(sex, job) %>% group_by(job) %>% summarise(num = n()) %>% arrange(desc(num)) %>% head(10)
female_job
```

### 2-5. 종교 유무에 따른 이혼율
```{r}
# 종교 변수 검토
class(welfare$religion)
table(welfare$religion)
```
```{r}
# 종교유무에 따라 1은 yes, 2는 no로 변경
welfare$religion <- ifelse(welfare$religion == 1, 'yes','no')
table(welfare$religion)
qplot(welfare$religion)
```

```{r}
# 혼인 변수 검토
class(welfare$marriage)
table(welfare$marriage)
```
```{r}
# 이혼 여부에 따른 파생변수 추가(group_marriage : 1은 marriage, 2는 divorce, 나머지는 NA로)
welfare$group_marriage <- ifelse(welfare$marriage == 1, 'marriage' , ifelse(welfare$marriage == 3, 'divorce', NA))
table(welfare$group_marriage)
```
```{r}
# 종교 유무에 따른 이혼율표 작성
reg_marr <- welfare %>% filter(!is.na(group_marriage))%>%group_by(religion, group_marriage) %>% select(religion, group_marriage) %>% summarise(n=n()) %>% mutate(tot_group = sum(n)) %>% mutate(pct = round(n/tot_group *100,1))
reg_marr
```
```{r}
divorce <- reg_marr %>% filter(group_marriage == 'divorce') %>% select(religion, pct)

divorce
```
```{r}
# 연령대 별로 이혼률표 작성
ageg_marriage <- welfare  %>% filter(!is.na(group_marriage)) %>% select(ageg, group_marriage) %>% group_by(ageg, group_marriage) %>% summarise(n = n()) %>% mutate(tot_group = sum(n)) %>% mutate(pct = round(n/tot_group*100,1))
ageg_marriage
```
```{r}
ageg_divorce <- ageg_marriage %>% filter(ageg != 'young' & group_marriage == 'divorce') %>% select('ageg', 'pct')
ageg_divorce
```

```{r}
# 종교 유무에 따른 이혼률의 차이가 연령대별로 다른지 확인
rel_div_ageg <- welfare %>% filter(!is.na(marriage) & group_marriage == 'divorce' & ageg != 'young') %>% select(ageg, religion, marriage) %>% group_by(ageg, religion) %>% summarise(n= n()) %>% mutate(tot_group = sum(n)) %>% mutate(pct = round(n/tot_group*100,1))
rel_div_ageg
```

```{r}
ggplot(rel_div_ageg, aes(ageg, pct, fill=religion)) + geom_col(position = 'dodge')
```


### 2-6. 지역별로 연령대 비율
```{r}
table(welfare$code_region)
```
```{r}
# 지역 코드 목록
list_region <- data.frame(code_region = (1:7), region = c('서울','수도권(인천/경기)','부산/경남/울산','대구/경북','대전/충남','강원/충북','광주/전남/전북/제주도'))
list_region
```
```{r}
welfare <- left_join(welfare, list_region, by = 'code_region')
head(welfare)
welfare %>% select(code_region, region) %>% head(10)
str(welfare)
```
```{r}
# 지역별 연령대 비율표
reg_ageg <- welfare %>% select(region, ageg) %>%group_by(region, ageg) %>% summarise(n=n()) %>% mutate(tot = sum(n)) %>% mutate(pct = round(n/tot*100, 2))
reg_ageg
```

```{r}
ggplot(reg_ageg, aes(region, pct, fill=ageg)) + geom_col() +coord_flip()
```
```{r}
# 노년층 비율이 높은순으로 막대정렬
list_order_old <- reg_ageg %>% filter(ageg=='old') %>% arrange(pct)
list_order_old
```
```{r}
order <- list_order_old$region
order
```
```{r}
ggplot(reg_ageg, aes(region, pct, fill=ageg)) + geom_col() +coord_flip() + scale_x_discrete(limits = order)

```
```{r}
reg_ageg$ageg <- factor(reg_ageg$ageg, levels = c('old','middle','young'))
class(reg_ageg$ageg)
levels(reg_ageg$ageg)
```

